- name: Deploy images
  hosts: hypervisor
  tags:
    - deploy_aio_image
  tasks:
    - name: Gather variables for each operating system
      include: prepare_hypervisor.yml

    - name: Create AIO vm
      command: >
        virt-install --vcpus {{aio_cpu_num}} --memory {{aio_memory_mb}}
                     --disk {{global_disk_pool_path}}/{{aio_image_filename}}
                     --network bridge={{global_host_bridge}},model=virtio,mac=0c:c4:7a:aa:ff:f1
                     --network bridge={{global_ironic_bridge}},model=virtio,,mac=0c:c4:7a:aa:ff:f2
                     --name {{aio_build_name}} --os-variant auto --import --os-type linux --boot hd
                     --noautoconsole
